services:
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
